version: '3.7'

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - redis-cache:/data
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - '3000'
    links:
      - redis
    ports:
      - '3000:3000'
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
    depends_on:
      - redis
    command: npm run start
volumes:
  redis-cache:
    driver: local